name: Build and Deploy Unity WebGL

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build Unity Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Library folder
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: Library-

      - name: Build Unity Project
        uses: game-ci/unity-builder@v4.5.0
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          # buildName: TuJuegoWebGL # Opcional: puedes darle un nombre específico
          # buildPath: build/WebGL # Opcional: El path de salida por defecto ya es 'build/<targetPlatform>'

      - name: Upload Unity Build Artifact
        uses: actions/upload-artifact@v4 # Usa actions/upload-artifact para subir el resultado
        with:
          name: webgl-build # Un nombre para tu artefacto
          path: build/WebGL/ # La ruta donde Unity Builder guarda la compilación WebGL
          retention-days: 1 # Opcional: Cuántos días quieres retener el artefacto

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Download Unity Build Artifact
        uses: actions/download-artifact@v4 # Descarga el artefacto generado en el trabajo 'build'
        with:
          name: webgl-build # Debe coincidir con el nombre usado en upload-artifact
          path: ./build/WebGL # Descarga el contenido del artefacto a esta ruta

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Aquí, la ruta ahora apunta a la carpeta donde descargaste el artefacto
          path: ./build/WebGL 
          name: Build-WebGL # Puedes mantener el mismo nombre o cambiarlo si lo deseas

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
